[workspace]
members = ["packages/os"]
exclude = ["packages/os/vendor/trouble-host"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
repository = "https://github.com/patrikduksin/cycling"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
debug = 2
panic = "abort"
overflow-checks = true

[patch.crates-io]
trouble-host = { path = "packages/os/vendor/trouble-host" }
