pub mod ant_protocol;
#[cfg(feature = "hardware")]
pub mod bluetooth;
#[cfg(all(feature = "hardware", feature = "bulk-maintenance"))]
pub mod bulk_maintenance;
pub mod companion;
pub mod companion_sensors;
pub mod companion_startup;
#[cfg(feature = "hardware")]
pub mod companion_uart;
#[cfg(feature = "hardware")]
pub mod crash_rtc;
#[cfg(feature = "hardware")]
pub mod display;
#[cfg(feature = "hardware")]
pub mod gps_uart;
pub mod input;
pub mod power_transition;
#[cfg(feature = "hardware")]
pub mod psram;
#[cfg(feature = "hardware")]
pub mod sdmmc;
pub mod sdmmc_probe;
#[cfg(feature = "hardware")]
pub mod sleep;
pub mod sound_protocol;
#[cfg(feature = "hardware")]
pub mod storage;
#[cfg(feature = "hardware")]
pub mod touch;
pub mod uart_ring;
#[cfg(feature = "hardware")]
pub mod usb;
#[cfg(feature = "hardware")]
pub mod wifi;
